version = 1

exclude_patterns = [
  "/src/Mireya.Database.Postgres/**",
  "/src/Mireya.Database.Sqlite/**",
  "/src/Mireya.ApiClient/Generated/**",
  "/src/Mireya.ApiClient/Migrations/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "prettier"
