<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>5a848976-55c0-42d0-92c0-6e0f797393cf</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.2.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mireya.Api\Mireya.Api.csproj" />
      <ProjectReference Include="..\Mireya.Web\Mireya.Web.csproj" />
    </ItemGroup>

</Project>
