// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mireya.ApiClient.Data;

#nullable disable

namespace Mireya.ApiClient.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260823101709_RemoveCampaignPlaybackPolicy")]
    partial class RemoveCampaignPlaybackPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Mireya.ApiClient.Data.BackendAsset", b =>
                {
                    b.Property<Guid>("BackendInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BackendInstanceId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("BackendAssets");
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.BackendCampaign", b =>
                {
                    b.Property<Guid>("BackendInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BackendInstanceId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("BackendCampaigns");
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.BackendCredential", b =>
                {
                    b.Property<Guid>("BackendInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedAccessToken")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EncryptedPassword")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EncryptedRefreshToken")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("BackendInstanceId");

                    b.ToTable("BackendCredentials");
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.BackendInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentBackend")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseUrl")
                        .IsUnique();

                    b.HasIndex("IsCurrentBackend")
                        .IsUnique()
                        .HasFilter("\"IsCurrentBackend\"");

                    b.ToTable("BackendInstances");
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.ClientSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ClientSettings");
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.DownloadedAsset", b =>
                {
                    b.Property<Guid>("BackendInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("BackendInstanceId", "AssetId");

                    b.HasIndex("IsDownloaded");

                    b.ToTable("DownloadedAssets");
                });

            modelBuilder.Entity("Mireya.Database.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageFit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailSource")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Assets", t =>
                        {
                            t.HasCheckConstraint("CK_Assets_DurationSeconds_Positive", "\"DurationSeconds\" IS NULL OR \"DurationSeconds\" > 0");

                            t.HasCheckConstraint("CK_Assets_FileSizeBytes_NonNegative", "\"FileSizeBytes\" IS NULL OR \"FileSizeBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("Mireya.Database.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Mireya.Database.Models.CampaignAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CampaignId", "Position")
                        .IsUnique();

                    b.ToTable("CampaignAssets", t =>
                        {
                            t.HasCheckConstraint("CK_CampaignAssets_DurationSeconds_Positive", "\"DurationSeconds\" IS NULL OR \"DurationSeconds\" > 0");

                            t.HasCheckConstraint("CK_CampaignAssets_Position_Positive", "\"Position\" > 0");
                        });
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.BackendAsset", b =>
                {
                    b.HasOne("Mireya.Database.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mireya.ApiClient.Data.BackendInstance", null)
                        .WithMany()
                        .HasForeignKey("BackendInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.BackendCampaign", b =>
                {
                    b.HasOne("Mireya.ApiClient.Data.BackendInstance", null)
                        .WithMany()
                        .HasForeignKey("BackendInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mireya.Database.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.BackendCredential", b =>
                {
                    b.HasOne("Mireya.ApiClient.Data.BackendInstance", null)
                        .WithMany()
                        .HasForeignKey("BackendInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mireya.ApiClient.Data.DownloadedAsset", b =>
                {
                    b.HasOne("Mireya.ApiClient.Data.BackendInstance", null)
                        .WithMany()
                        .HasForeignKey("BackendInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mireya.Database.Models.CampaignAsset", b =>
                {
                    b.HasOne("Mireya.Database.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mireya.Database.Models.Campaign", "Campaign")
                        .WithMany("CampaignAssets")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Mireya.Database.Models.Campaign", b =>
                {
                    b.Navigation("CampaignAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
